### ISSUE TITLE
A no-clobber type option would be useful

### ISSUE THREAD

**Issue by SB47x** [stabbedbybrick/freevine#45]
It'd be handy for freevine to not re-download a video if it's already on disk.

When the tool knows what the output filename will be - the "INFO : Save Name: " line in the output log - it could check if that file already exists. If it does, skip downloading it. Something like wget's no-clobber flag, I guess.

It'd be useful to me right now because I'm downloading things from All4, and there are a few episodes that will repeatedly error out and fail to download, but if you keep trying they'll eventually work. I've got a shell script with the list of things I want to download, and I just leave it going, but for the things that fail to download, it'd be handy if I could just call the shell script again to download the failed downloads.

Right now though, if you try to redownload something you already have, it'll download it again but leave the .MUX.mkv file. I guess it fails when trying to rename it, but there's nothing in the output log to indicate that anything went wrong.

For info, when it errors out, it's usually "400 Client Error: Bad Request for url: ..."

I try it again and it fails again. And again. Until it works. Running the exact same command over and over. Not sure if it's a bug in freevine or just All4 being weird. No VPN or smart DNS or anything in use.

**Comment by SB47x** [comment]
Ah, fantastic. Yeah I'm using 1.1.0 and I'd never used a previous version. I'll grab the fixed version.

I'm using the latest version, in the UK, using no VPN or proxy or any smart DNS stuff, using my own credentials so I can't see what the issue could be.

**Comment by SB47x** [comment]
Yep, that's working well in the new version. It's skipping things that already exist.

It's still throwing the 400 errors sometimes though, and oddly enough it does it on things that are already downloaded.

```
16:05:27.952 INFO : [episodename] already exist. Skipping download

16:05:27.952 INFO : Using cached tokens
16:05:28.025 DEBUG : https://api.channel4.com:443 "GET /online/v1/vod/stream/36607-003?client=android-mod HTTP/1.1" 200 2709
16:05:28.173 DEBUG : http://ak.dash01.stream.c4assets.com:80 "GET /wvmod-stream/CH4_33_05_42_36607003001001_002.mpd?c3.ri=13629397883449412228 HTTP/1.1" 400 371
Traceback (most recent call last):
  File "/mounts/nvme/freevine.fixed/freevine.py", line 15, in <module>
    cli()
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/mounts/nvme/freevine.fixed/utils/commands.py", line 80, in get
    Service(config, **kwargs)
  File "services/channel4/channel4.py", line 61, in __init__
    self.get_options()
  File "services/channel4/channel4.py", line 358, in get_options
    self.download(download, title)
  File "services/channel4/channel4.py", line 361, in download
    self.res, manifest, token = self.get_mediainfo(stream.id, self.quality)
  File "services/channel4/channel4.py", line 287, in get_mediainfo
    heights, self.soup = get_heights(self.client, manifest)
  File "/mounts/nvme/freevine.fixed/utils/utilities.py", line 120, in get_heights
    r.raise_for_status()
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://ak.dash01.stream.c4assets.com/wvmod-stream/CH4_33_05_42_36607003001001_002.mpd?c3.ri=13629397883449412228
```
