### ISSUE TITLE
Some PlutoTV episodes are not working

### ISSUE THREAD

**Issue by Paamayim-Nekudotayim** [stabbedbybrick/freevine#46]
Hello,

Some episodes (from same season or not) fails to download.

Working:
freevine.py get -e S03E301 https://pluto.tv/fr/on-demand/series/60006e2b6d0bea001b05d330/season/3/episode/602a33646c2a2d00140fd288

Not working:
freevine.py get -e S03E302 https://pluto.tv/fr/on-demand/series/60006e2b6d0bea001b05d330/season/3/episode/60007e7850e458001a79b1c3

```
Traceback (most recent call last):
  File "D:\freevine\freevine.py", line 15, in <module>
    cli()
  File "C:\Users\Dan\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dan\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Dan\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dan\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dan\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\freevine\utils\commands.py", line 80, in get
    Service(config, **kwargs)
  File "D:\freevine\services\pluto\pluto.py", line 51, in __init__
    self.get_options()
  File "D:\freevine\services\pluto\pluto.py", line 317, in get_options
    self.download(download, title)
  File "D:\freevine\services\pluto\pluto.py", line 321, in download
    manifest = self.get_playlist(stream.data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\freevine\services\pluto\pluto.py", line 193, in get_playlist
    return self.get_dash(stitched)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\freevine\services\pluto\pluto.py", line 151, in get_dash
    parse = urlparse(new_base)
                     ^^^^^^^^
```

The issue is located on MPD URL discovery: URL format is not the same between episodes or seasons. Seasons 4, 5, 6, 8 works, not other ones.

**Comment by stabbedbybrick** [comment]
The latest update to main branch should fix this. Give it a test drive and see if it works.

**Comment by Paamayim-Nekudotayim** [comment]
All episodes from all seasons now work. Awesome!
