### ISSUE TITLE
Pluto TV download is incorrect

### ISSUE THREAD

**Issue by easy20192018** [stabbedbybrick/freevine#73]
**Describe the bug**
If I want to download certain films. he tells me he downloaded it. Then I look in the download folder. There is an 800kb file there. But it's just the introduction that this video is for ages 16 and up. And not the film.

the command
"freevine.py get -m https://pluto.tv/de/on-demand/movies/6255249128c6dd00132c185c"

use Freevine 1.1.7

**Comment by stabbedbybrick** [comment]
This has been fixed in the latest commit: https://github.com/stabbedbybrick/freevine/commit/3ffbd8877b34f3e953a6e92dda5f2fb827d39351

Fetch the new update and it should work properly.

**Comment by Gustavox10** [comment]
Hello, thank you very much for your great work! I tried to download this Latin America  series from plutotv, and it gave me an error.
freevine.py get --no-cache --season S01 https://pluto.tv/stream-latam/on-demand/series/5f85afc5652fb5001add9be2/details

You could review it! Mexico IP
Thank you!

**Comment by stabbedbybrick** [comment]
> Hello, thank you very much for your great work! I tried to download this Latin America series from plutotv, and it gave me an error. freevine.py get --no-cache --season S01 https://pluto.tv/stream-latam/on-demand/series/5f85afc5652fb5001add9be2/details
> 
> You could review it! Mexico IP Thank you!

I can't help you without knowing what the error is.

**Comment by Gustavox10** [comment]
error is:

❯_freevine v1.1.7

17:49:08.034 INFO : PlutoTV
17:49:10.858 INFO : Los Tres Chiflados: 1 Season(s), 158 Episode(s)

Traceback (most recent call last):
  File "F:\2024\plutotv\freevine.py", line 15, in <module>
    cli()
  File "C:\Users\Gustavo\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Gustavo\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Gustavo\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Gustavo\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Gustavo\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "F:\2024\plutotv\utils\commands.py", line 90, in get
    Service(config, **kwargs)
  File "services\pluto\pluto.py", line 58, in __init__
    self.get_options()
  File "services\pluto\pluto.py", line 350, in get_options
    self.download(download, title)
  File "services\pluto\pluto.py", line 353, in download
    manifest = self.get_playlist(stream.data)
  File "services\pluto\pluto.py", line 227, in get_playlist
    manifest = self.get_dash(dash)
  File "services\pluto\pluto.py", line 153, in get_dash
    r.raise_for_status()
  File "C:\Users\Gustavo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cfd-v4-service-stitcher-dash-use1-1.prd.pluto.tv/v2None?appName=web&appVersion=na&clientID=d854e82a-c39e-11ee-8e24-f430b99564be&deviceDNT=0&deviceId=unknown&clientModelNumber=na&serverSideAds=false&deviceMake=unknown&deviceModel=web&deviceType=web&deviceVersion=unknown&sid=d854e82b-c39e-11ee-a0d8-f430b99564be&drmCapabilities=widevine%3AL3


Thanks for the help!

**Comment by stabbedbybrick** [comment]
@Gustavox10:

This should now be fixed with the latest commit. Fetch the new update and try again.

**Comment by Gustavox10** [comment]
> @Gustavox10:
> 
> This should now be fixed with the latest commit. Fetch the new update and try again.

Thank you very much", you are a genius!

**Comment by stabbedbybrick** [comment]
> > @Gustavox10:
> > This should now be fixed with the latest commit. Fetch the new update and try again.
> 
> Thank you very much", you are a genius!

Hardly. But I'm glad to hear it's working for you.

**Comment by stabbedbybrick** [comment]
Closing this issue as it's been resolved.
