### ISSUE TITLE
Downloading a single season does not work (UKTV)

### ISSUE THREAD

**Issue by OevreFlataeker** [stabbedbybrick/freevine#77]
**Describe the bug**
I just want to download a single season of a series, but freevine does not honor the selection

**To Reproduce**
freevine.py get --season 4 https://uktvplay.co.uk/shows/the-architecture-the-railways-built/watch-online  -sv res=720

Freevine lists that there are 4 seasons found, but it starts downloading with episode 4 of season 1 instead of episode 1 of season 4

```
F:\freevine>freevine.py get --season 4 https://uktvplay.co.uk/shows/the-architecture-the-railways-built/watch-online  -sv res=720

❯_freevine v1.1.7

18:07:49.784 INFO : UKTV Play
18:07:50.295 INFO : The Architecture the Railways Built: 4 Season(s), 40 Episode(s)

18:07:51.542 INFO : The Architecture the Railways Built S01E04
...
...
18:07:51.904 INFO : Sub 24e282b6-7c57-4349-80bb-63fa03e43469 | en | 1 Segment | ~43m52s
18:07:51.904 WARN : Writing meta json
18:07:51.905 INFO : Save Name: The.Architecture.the.Railways.Built.S01E04.720p.UKTV.WEB-DL.AAC2.0.H.264
``` 

**Expected behavior**
Specified season is downloaded

**Additional context**
Downloading individual episodes of the season work as expected

**Comment by OevreFlataeker** [comment]
Need to correct myself! Even downloading an individual episode currently doesn't work anymore :-(

```
.\freevine.py get --episode https://uktvplay.co.uk/shows/the-architecture-the-railways-built/series-4/episode-1/6320633720112  -sv res=720

❯_freevine v1.1.7

18:15:05.075 INFO : UKTV Play
Traceback (most recent call last):
  File "F:\freevine\freevine.py", line 15, in <module>
    cli()
  File "F:\freevine\.venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "F:\freevine\.venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "F:\freevine\.venv\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "F:\freevine\.venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "F:\freevine\.venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "F:\freevine\utils\commands.py", line 90, in get
    Service(config, **kwargs)
  File "F:\freevine\services\uktvplay\uktvplay.py", line 51, in __init__
    self.get_options()
  File "F:\freevine\services\uktvplay\uktvplay.py", line 199, in get_options
    downloads, title = get_downloads(self)
  File "F:\freevine\utils\options.py", line 160, in get_downloads
    downloads, title = stream.get_episode_from_url(stream.episode)
  File "F:\freevine\services\uktvplay\uktvplay.py", line 172, in get_episode_from_url
    house_number = re.search(r'house_number="(.+?)"', html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Using "get -t" correctly lists all 40 episodes though

**Comment by stabbedbybrick** [comment]
Your command is incorrect:
`freevine.py get --season s04 https://uktvplay.co.uk/shows/the-architecture-the-railways-built/watch-online`

Downloading episodes the normal way with `--episode s04e01 URL` works fine.

Downloading by episode URL was broken but has already been fixed. Just pull the new updates from main branch.

**Comment by OevreFlataeker** [comment]
Confirmed! Now works as expected!
