### ISSUE TITLE
CTV 

### ISSUE THREAD

**Issue by FuNFooKaS** [stabbedbybrick/freevine#81]
**Describe the bug**

**To Reproduce**
```
python freevine.py get --season S13 https://www.ctv.ca/shows/moonshiners

❯_freevine v1.1.7

23:00:48.592 INFO : CTV
23:00:48.592 INFO : + Adding cookie data
23:00:52.938 INFO : Moonshiners (2011): 13 Season(s), 230 Episode(s)

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\freevine-main\freevine.py", line 15, in <module>
    cli()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Admin\Desktop\freevine-main\utils\commands.py", line 90, in get
    Service(config, **kwargs)
  File "services\ctv\ctv.py", line 53, in __init__
    self.get_options()
  File "services\ctv\ctv.py", line 400, in get_options
    self.download(download, title)
  File "services\ctv\ctv.py", line 404, in download
    self.res, audio = self.get_mediainfo(manifest, self.quality)
  File "services\ctv\ctv.py", line 256, in get_mediainfo
    content = asyncio.run(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "services\ctv\ctv.py", line 253, in parse_manifests
    return await asyncio.gather(*tasks)
  File "services\ctv\ctv.py", line 246, in fetch_manifests
    raise ConnectionError(f"{response}")
ConnectionError: <Response [401 Unauthorized]>
```

**Expected behavior**
i can watch it in browser  i added new cookies as well

**Comment by stabbedbybrick** [comment]
Content that requires a TV Provider is currently not supported since I don't have the access to see what the authentication process looks like.

**Comment by stabbedbybrick** [comment]
Since this has been solved with https://github.com/stabbedbybrick/freevine/commit/690b57c0395abf8b4da987d43435438ce9af6f18, I'll close this as completed.
