### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Maverick20256** [stabbedbybrick/freevine#94]
im getting this:

❯_freevine v1.1.8

20:00:56.181 ←[4m←[32mINFO←[0m : ←[1mALL4←[0m
20:00:56.181 ←[4m←[32mINFO←[0m : + Adding service profile
Traceback (most recent call last):
  File "C:\Users\Maverick\Desktop\freevine-main\freevine.py", line 15, in <module>
    cli()
  File "C:\Users\Maverick\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Maverick\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Maverick\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Maverick\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Maverick\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Maverick\Desktop\freevine-main\utils\commands.py", line 89, in get
    Service, config = service_manager.get_service(url)
  File "C:\Users\Maverick\Desktop\freevine-main\utils\manager.py", line 79, in get_service
    self.config.update(yaml.safe_load(f))
ValueError: dictionary update sequence element #0 has length 1; 2 is required

same error with cbc

**Comment by Maverick20256** [comment]
FIXED NOW
